from src.config.default import _CN as cfg

cfg.TRAINER.MSLR_MILESTONES = [5, 10, 15, 20, 25]

cfg.TRAINER.TRUE_LR=1e-3
cfg.TRAINER.BACKBONE_LR=1e-3
cfg.TRAINER.DATA_SAMPLER = 'scene_balance'
cfg.TRAINER.N_SAMPLES_PER_SUBSET = 1024
cfg.TRAINER.SCORE_THRESH = 0.5
cfg.TRAINER.RANSAC_THRESH=48
cfg.TRAINER.ADAMW_DECAY = 1e-06
cfg.TRAINER.WARMUP_STEP = 2000
cfg.TRAINER.GRADIENT_CLIPPING = 0.5

cfg.MODEL.CODE_NUM=100
cfg.MODEL.D_MODEL=256
cfg.MODEL.RESNETFPN.BLOCK_DIMS = [128, 256, 256]
cfg.MODEL.RESNETFPN.STRIDES = [2, 2, 1]
cfg.MODEL.RESNETFPN.INITIAL_DIM = 64
cfg.MODEL.TRANS_BLOCK_NUM=6
cfg.MODEL.RGB=True

cfg.DATASET.RESOLUTION=720
cfg.DATASET.RANDOM_CROP=False

cfg.LOSS.SCALE=2.0

cfg.EXP.PIMAE_LR = 1e-3

# ========== Feature Match (paper config for NuScenes) ==========
cfg.FEATURE_MATCH.NEW_PIPELINE = True
cfg.FEATURE_MATCH.NUSCENES = True

cfg.FEATURE_MATCH.SAMPLE_POINT = 512
cfg.FEATURE_MATCH.RGB = True

# image backbone
cfg.FEATURE_MATCH.DUST_BACKBONE = True
cfg.FEATURE_MATCH.DUST_WITH_RESNET = True
cfg.FEATURE_MATCH.IMAGE_ENC_DIM = 256

# point backbone
cfg.FEATURE_MATCH.POINT_BACKBONE = 'pt'
cfg.FEATURE_MATCH.PT_NUM_NODE = 1280
cfg.FEATURE_MATCH.PT_NUM_PROXY = 512
cfg.FEATURE_MATCH.PT_NUM_SA_LAYER = 3
cfg.FEATURE_MATCH.PT_NUM_HEAD = 8
cfg.FEATURE_MATCH.PT_POINT_FEAT_DIM = 3
cfg.FEATURE_MATCH.PT_EMBED_DIM = 256
cfg.FEATURE_MATCH.PT_MLP_DIM = 1024
cfg.FEATURE_MATCH.PT_ATTENTION_DROPOUT = 0.1
cfg.FEATURE_MATCH.PT_MLP_DROPOUT = 0.1

cfg.FEATURE_MATCH.NUM_CLUSTER = 512
cfg.FEATURE_MATCH.PIMAE = True

# feature fusion
cfg.FEATURE_MATCH.COFI_FUSION = True
cfg.FEATURE_MATCH.COFI_FUSION_NORM = False
cfg.FEATURE_MATCH.COFI_NO_PCD_POS = False
cfg.FEATURE_MATCH.COFI_NUM_LAYER = 4

# coarse match
cfg.FEATURE_MATCH.COARSE_PATCH_SIZE = 16
cfg.FEATURE_MATCH.COARSE_MATCH = True
cfg.FEATURE_MATCH.COARSE_MATCH_TYPE = 'bce_dense'
cfg.FEATURE_MATCH.DENSE_STD = 0.0
cfg.FEATURE_MATCH.COARSE_MATCH_NORM = 'l2_norm'
cfg.FEATURE_MATCH.UPSAMPLE = False
cfg.FEATURE_MATCH.DENSE_TEMP = True
cfg.FEATURE_MATCH.BCE_SAMPLE = True
cfg.FEATURE_MATCH.COARSE_DENSE_WINDOW = 3
cfg.FEATURE_MATCH.COARSE_WINDOW_GT = False
cfg.FEATURE_MATCH.COARSE_INTRA = True
cfg.FEATURE_MATCH.COARSE_EUC = True
cfg.FEATURE_MATCH.ATT_LOSS = True

# fine match
cfg.FEATURE_MATCH.FINE_MATCH = True
cfg.FEATURE_MATCH.FINE_MATCH_NORM = 'dim_norm'
cfg.FEATURE_MATCH.FINE_RESNET = True
cfg.FEATURE_MATCH.FINE_RESNET_UP = True
cfg.FEATURE_MATCH.FINE_RESNET_ONLY = True
cfg.FEATURE_MATCH.FINE_LOSS_TYPE = 'dense'
cfg.FEATURE_MATCH.FINE_SOFTMAX = True
cfg.FEATURE_MATCH.FINE_PATCH_AUG = True

# cofi pipeline
cfg.FEATURE_MATCH.COFII2P_PIPE = True
